# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/2dde360a-a667-4c70-8db1-c51270d152f3";
  #     fsType = "btrfs";
  #     options = [ "subvol=root" ];
  #   };

  # fileSystems."/nix" =
  #   { device = "/dev/disk/by-uuid/2dde360a-a667-4c70-8db1-c51270d152f3";
  #     fsType = "btrfs";
  #     options = [ "subvol=nix" ];
  #   };

  # fileSystems."/persist" =
  #   { device = "/dev/disk/by-uuid/2dde360a-a667-4c70-8db1-c51270d152f3";
  #     fsType = "btrfs";
  #     options = [ "subvol=persist" ];
  #   };

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/D831-AF34";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/3c289d77-c67e-4149-9ec1-952dfb02e7b5"; }
  #   ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
